export const OPEN_SIGNUP_MODAL = 'OPEN_SIGNUP_MODAL';
export const CLOSE_SIGNUP_MODAL = 'CLOSE_SIGNUP_MODAL';
export const OPEN_SIGNUP_MODAL_2 = 'OPEN_SIGNUP_MODAL_2';
export const CLOSE_SIGNUP_MODAL_2 = 'CLOSE_SIGNUP_MODAL_2';